// <auto-generated />
using System;
using HUBDTE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HUBDTE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224201545_AddOutboxProcessingStartedAt")]
    partial class AddOutboxProcessingStartedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HUBDTE.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublishAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SapDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("SapDocumentId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_OutboxMessages_Status_CreatedAt");

                    b.HasIndex("Status", "ProcessingStartedAt")
                        .HasDatabaseName("IX_OutboxMessages_Status_ProcessingStartedAt");

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("HUBDTE.Domain.Entities.SapDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("DocEntry")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TipoDte")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("IX_SapDocuments_Status_UpdatedAt");

                    b.HasIndex("FilialCode", "DocEntry", "TipoDte")
                        .IsUnique()
                        .HasDatabaseName("UX_SapDocuments_Filial_DocEntry_TipoDte");

                    b.ToTable("SapDocuments", "dbo");
                });

            modelBuilder.Entity("HUBDTE.Domain.Entities.OutboxMessage", b =>
                {
                    b.HasOne("HUBDTE.Domain.Entities.SapDocument", "SapDocument")
                        .WithMany("OutboxMessages")
                        .HasForeignKey("SapDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SapDocument");
                });

            modelBuilder.Entity("HUBDTE.Domain.Entities.SapDocument", b =>
                {
                    b.Navigation("OutboxMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
