//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessDTEService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://processimportacion.webservices.dte.azurian.com", ConfigurationName="ProcessDTEService.ProcessDTEServicePortType")]
    public interface ProcessDTEServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:validarIdenInterno", ReplyAction="urn:validarIdenInternoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProcessDTEService.validarIdenInternoResponse> validarIdenInternoAsync(ProcessDTEService.validarIdenInternoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:importarDocumentos", ReplyAction="urn:importarDocumentosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProcessDTEService.importarDocumentosResponse> importarDocumentosAsync(ProcessDTEService.importarDocumentosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://processimportacion.webservices.dte.azurian.com/xsd")]
    public partial class DTEProcessRequest
    {
        
        private string apiKeyField;
        
        private string archivoField;
        
        private string dataField;
        
        private int resolucionSiiField;
        
        private bool resolucionSiiFieldSpecified;
        
        private int rutEmpresaField;
        
        private bool rutEmpresaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string apiKey
        {
            get
            {
                return this.apiKeyField;
            }
            set
            {
                this.apiKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int resolucionSii
        {
            get
            {
                return this.resolucionSiiField;
            }
            set
            {
                this.resolucionSiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resolucionSiiSpecified
        {
            get
            {
                return this.resolucionSiiFieldSpecified;
            }
            set
            {
                this.resolucionSiiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int rutEmpresa
        {
            get
            {
                return this.rutEmpresaField;
            }
            set
            {
                this.rutEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rutEmpresaSpecified
        {
            get
            {
                return this.rutEmpresaFieldSpecified;
            }
            set
            {
                this.rutEmpresaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://processimportacion.webservices.dte.azurian.com/xsd")]
    public partial class DTEProcessResponse
    {
        
        private string codigoInternoReceptorField;
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private string docDteField;
        
        private int idTipoDocumentoField;
        
        private bool idTipoDocumentoFieldSpecified;
        
        private string mapeadoField;
        
        private string mapeadoAnField;
        
        private long numeroFolioField;
        
        private bool numeroFolioFieldSpecified;
        
        private long rutReceptorField;
        
        private bool rutReceptorFieldSpecified;
        
        private int tipoReceptorElectronicoField;
        
        private bool tipoReceptorElectronicoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codigoInternoReceptor
        {
            get
            {
                return this.codigoInternoReceptorField;
            }
            set
            {
                this.codigoInternoReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string descripcionRespuesta
        {
            get
            {
                return this.descripcionRespuestaField;
            }
            set
            {
                this.descripcionRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string docDte
        {
            get
            {
                return this.docDteField;
            }
            set
            {
                this.docDteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int idTipoDocumento
        {
            get
            {
                return this.idTipoDocumentoField;
            }
            set
            {
                this.idTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoDocumentoSpecified
        {
            get
            {
                return this.idTipoDocumentoFieldSpecified;
            }
            set
            {
                this.idTipoDocumentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string mapeado
        {
            get
            {
                return this.mapeadoField;
            }
            set
            {
                this.mapeadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string mapeadoAn
        {
            get
            {
                return this.mapeadoAnField;
            }
            set
            {
                this.mapeadoAnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long numeroFolio
        {
            get
            {
                return this.numeroFolioField;
            }
            set
            {
                this.numeroFolioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroFolioSpecified
        {
            get
            {
                return this.numeroFolioFieldSpecified;
            }
            set
            {
                this.numeroFolioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long rutReceptor
        {
            get
            {
                return this.rutReceptorField;
            }
            set
            {
                this.rutReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rutReceptorSpecified
        {
            get
            {
                return this.rutReceptorFieldSpecified;
            }
            set
            {
                this.rutReceptorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int tipoReceptorElectronico
        {
            get
            {
                return this.tipoReceptorElectronicoField;
            }
            set
            {
                this.tipoReceptorElectronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoReceptorElectronicoSpecified
        {
            get
            {
                return this.tipoReceptorElectronicoFieldSpecified;
            }
            set
            {
                this.tipoReceptorElectronicoFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarIdenInterno", WrapperNamespace="http://processimportacion.webservices.dte.azurian.com", IsWrapped=true)]
    public partial class validarIdenInternoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://processimportacion.webservices.dte.azurian.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProcessDTEService.DTEProcessRequest request;
        
        public validarIdenInternoRequest()
        {
        }
        
        public validarIdenInternoRequest(ProcessDTEService.DTEProcessRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarIdenInternoResponse", WrapperNamespace="http://processimportacion.webservices.dte.azurian.com", IsWrapped=true)]
    public partial class validarIdenInternoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://processimportacion.webservices.dte.azurian.com", Order=0)]
        public bool @return;
        
        public validarIdenInternoResponse()
        {
        }
        
        public validarIdenInternoResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="importarDocumentos", WrapperNamespace="http://processimportacion.webservices.dte.azurian.com", IsWrapped=true)]
    public partial class importarDocumentosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://processimportacion.webservices.dte.azurian.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProcessDTEService.DTEProcessRequest request;
        
        public importarDocumentosRequest()
        {
        }
        
        public importarDocumentosRequest(ProcessDTEService.DTEProcessRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="importarDocumentosResponse", WrapperNamespace="http://processimportacion.webservices.dte.azurian.com", IsWrapped=true)]
    public partial class importarDocumentosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://processimportacion.webservices.dte.azurian.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProcessDTEService.DTEProcessResponse @return;
        
        public importarDocumentosResponse()
        {
        }
        
        public importarDocumentosResponse(ProcessDTEService.DTEProcessResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ProcessDTEServicePortTypeChannel : ProcessDTEService.ProcessDTEServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProcessDTEServicePortTypeClient : System.ServiceModel.ClientBase<ProcessDTEService.ProcessDTEServicePortType>, ProcessDTEService.ProcessDTEServicePortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProcessDTEServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ProcessDTEServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), ProcessDTEServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProcessDTEServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProcessDTEServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProcessDTEServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProcessDTEServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProcessDTEServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcessDTEService.validarIdenInternoResponse> ProcessDTEService.ProcessDTEServicePortType.validarIdenInternoAsync(ProcessDTEService.validarIdenInternoRequest request)
        {
            return base.Channel.validarIdenInternoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessDTEService.validarIdenInternoResponse> validarIdenInternoAsync(ProcessDTEService.DTEProcessRequest request)
        {
            ProcessDTEService.validarIdenInternoRequest inValue = new ProcessDTEService.validarIdenInternoRequest();
            inValue.request = request;
            return ((ProcessDTEService.ProcessDTEServicePortType)(this)).validarIdenInternoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcessDTEService.importarDocumentosResponse> ProcessDTEService.ProcessDTEServicePortType.importarDocumentosAsync(ProcessDTEService.importarDocumentosRequest request)
        {
            return base.Channel.importarDocumentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessDTEService.importarDocumentosResponse> importarDocumentosAsync(ProcessDTEService.DTEProcessRequest request)
        {
            ProcessDTEService.importarDocumentosRequest inValue = new ProcessDTEService.importarDocumentosRequest();
            inValue.request = request;
            return ((ProcessDTEService.ProcessDTEServicePortType)(this)).importarDocumentosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProcessDTEServiceHttpsSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProcessDTEServiceHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProcessDTEServiceHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProcessDTEServiceHttpsSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProcessDTEServiceHttpsSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://cloudtattersallqa.azurian.com/dte-ws-services/services/ProcessDTEService." +
                        "ProcessDTEServiceHttpsSoap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProcessDTEServiceHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://cloudtattersallqa.azurian.com/dte-ws-services/services/ProcessDTEService.P" +
                        "rocessDTEServiceHttpSoap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProcessDTEServiceHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://cloudtattersallqa.azurian.com/dte-ws-services/services/ProcessDTEService.P" +
                        "rocessDTEServiceHttpSoap12Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProcessDTEServiceHttpsSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://cloudtattersallqa.azurian.com/dte-ws-services/services/ProcessDTEService." +
                        "ProcessDTEServiceHttpsSoap12Endpoint/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ProcessDTEServiceHttpsSoap11Endpoint,
            
            ProcessDTEServiceHttpSoap11Endpoint,
            
            ProcessDTEServiceHttpSoap12Endpoint,
            
            ProcessDTEServiceHttpsSoap12Endpoint,
        }
    }
}
